# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: post_service.proto for package 'postservice'

require 'grpc'
require 'post_service_pb'

module Postservice
  module PostService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'postservice.PostService'

      rpc :CreatePost, ::Postservice::CreatePostRequest, ::Postservice::CreatePostResponse
    end

    Stub = Service.rpc_stub_class
  end
end
