# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_service.proto

require 'google/protobuf'


descriptor_data = "\n\x12post_service.proto\x12\x0bpostservice\"I\n\x11\x43reatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x12\n\nmedia_urls\x18\x03 \x03(\t\"5\n\x12\x43reatePostResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\\\n\x0bPostService\x12M\n\nCreatePost\x12\x1e.postservice.CreatePostRequest\x1a\x1f.postservice.CreatePostResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Postservice
  CreatePostRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("postservice.CreatePostRequest").msgclass
  CreatePostResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("postservice.CreatePostResponse").msgclass
end
