version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      - RACK_ENV=development
      - DB_HOST=db
      - DB_USER=whizzly
      - DB_PASSWORD=whizzly_password
      - DB_NAME=whizzly_post_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=whizzly_post_db
      - MYSQL_USER=whizzly
      - MYSQL_PASSWORD=whizzly_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
