version: '3.8'
services:
  app1:
    build:
      context: .
    ports:
      - "9292"
    environment:
      RACK_ENV: production
    deploy:
      replicas: 2          # Gunakan 2 container untuk mendukung multi-core
      resources:
        limits:
          cpus: "1"        # Setiap container menggunakan 1 core CPU
          memory: 512M     # Batas memori per container
    volumes:
      - .:/usr/src/app     # Untuk development (opsional)
      - ./tmp:/app/tmp
