source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sqlite3'
gem 'puma'      #  Puma untuk mendukung multi-threading dan multi-core
gem 'rack'      # Middleware Rack untuk thread safety
